# GitHub Pages configuration
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Windows PE Basic Enhanced | TheDoggyBrad

# Set the main page
index.md: README.md
